INSERT INTO USERTABLE (USERNAME, PASSWORD, EMAIL) VALUES ('Ante', 'password123', 'ante@mail.com')
INSERT INTO USERTABLE (USERNAME, PASSWORD, EMAIL) VALUES ('Chris', 'password123', 'chris@mail.com')
INSERT INTO USERTABLE (USERNAME, PASSWORD, EMAIL) VALUES ('Samuel', 'password123', 'samuel@mail.com')
INSERT INTO MEMES (PICURL, DESCRIPTION, MEMECREATEDBYUSER) VALUES ('https://i.redd.it/uqk46zan8zo81.jpg','hej Elon!', 'Ante')
INSERT INTO MEMES (PICURL, DESCRIPTION, MEMECREATEDBYUSER) VALUES ('https://i.imgur.com/x51rrjw.jpeg','lol', 'Chris')
INSERT INTO MEMES (PICURL, DESCRIPTION, MEMECREATEDBYUSER) VALUES ('https://i.redd.it/9iodhe6ss2p81.jpg','hihihi xD!', 'Ante')
